// <auto-generated />
using System;
using JobMatchAI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobMatchAI.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Alumni", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CurrentEmployer")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("current_employer");

                    b.Property<string>("CurrentPosition")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("current_position");

                    b.Property<DateOnly>("GraduationDate")
                        .HasColumnType("date")
                        .HasColumnName("graduation_year");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("program");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("alumni");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Certification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CredentialId")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("credential_id");

                    b.Property<DateTime>("DateIssued")
                        .HasColumnType("timestamp")
                        .HasColumnName("date_issued");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("expiry_date");

                    b.Property<string>("IssuingAuthority")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("issuing_authority");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("VerificationUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("verification_url");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("certifications");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Employer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyDescription")
                        .HasColumnType("text")
                        .HasColumnName("company_description");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("company_name");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("industry");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("logo_url");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Website")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("website");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("employers");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.EmploymentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlumniId")
                        .HasColumnType("uuid")
                        .HasColumnName("alumni_id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("company_name");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_current");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("position");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("text")
                        .HasColumnName("responsibilities");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("AlumniId");

                    b.ToTable("employment_histories");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Internship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("company_name");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("position");

                    b.Property<string>("SkillsGained")
                        .HasColumnType("varchar(200)")
                        .HasColumnName("skills_gained");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<string>("Supervisor")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("supervisor");

                    b.Property<string>("SupervisorEmail")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("supervisor_email");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("internships");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.JobPosting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Applications")
                        .HasColumnType("int")
                        .HasColumnName("applications");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("EmployerId")
                        .HasColumnType("uuid")
                        .HasColumnName("employer_id");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("employment_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bool")
                        .HasColumnName("is_active");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<decimal?>("MaxSalary")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("max_salary");

                    b.Property<int>("MinExperienceYears")
                        .HasColumnType("int")
                        .HasColumnName("min_experience_years");

                    b.Property<decimal?>("MinSalary")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("min_salary");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("posted_date");

                    b.Property<string>("PreferredSkills")
                        .HasColumnType("varchar(150)")
                        .HasColumnName("preferred_skills");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("requirements");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("title");

                    b.Property<int>("Views")
                        .HasColumnType("int")
                        .HasColumnName("views");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("job_postings");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.JobSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bool")
                        .HasColumnName("is_required");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_posting_id");

                    b.Property<int?>("MinimumProficiencyLevel")
                        .HasColumnType("int")
                        .HasColumnName("min_proficiency_level");

                    b.Property<int?>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("JobPostingId", "SkillId")
                        .IsUnique();

                    b.ToTable("job_skills");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.MatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double?>("EmployabilityScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("employability_score");

                    b.Property<string>("FeatureContributions")
                        .HasColumnType("text")
                        .HasColumnName("feature_contributions");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("generated_at");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("hire_date");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_posting_id");

                    b.Property<string>("MatchExplanation")
                        .HasColumnType("text")
                        .HasColumnName("match_explanation");

                    b.Property<double>("MatchScore")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("match_score");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<bool?>("WasApplied")
                        .HasColumnType("boolean")
                        .HasColumnName("was_applied");

                    b.Property<bool?>("WasHired")
                        .HasColumnType("boolean")
                        .HasColumnName("was_hired");

                    b.Property<bool?>("WasViewed")
                        .HasColumnType("boolean")
                        .HasColumnName("was_viewed");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId");

                    b.HasIndex("StudentId", "JobPostingId")
                        .IsUnique();

                    b.ToTable("match_results");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.PlacementRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("JobPostingId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_posting_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("PlacementDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("placement_date");

                    b.Property<string>("PlacementStatus")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("placement_status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id");

                    b.HasIndex("JobPostingId");

                    b.HasIndex("StudentId", "JobPostingId")
                        .IsUnique();

                    b.ToTable("placement_records");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AlumniId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("IconUrl")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("icon_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("OntologyId")
                        .HasColumnType("text")
                        .HasColumnName("ontology_id");

                    b.HasKey("Id");

                    b.HasIndex("AlumniId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("skills");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("GraduationDate")
                        .HasColumnType("date")
                        .HasColumnName("graduation_date");

                    b.Property<decimal>("Gwa")
                        .HasColumnType("decimal(3,2)")
                        .HasColumnName("gwa");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("program");

                    b.Property<string>("ResumeFilePath")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("resume_file_path");

                    b.Property<string>("ResumeText")
                        .HasColumnType("text")
                        .HasColumnName("resume_text");

                    b.Property<string>("StudentIdNumber")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasColumnName("student_id_number");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("YearLevel")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("year_level");

                    b.HasKey("Id");

                    b.HasIndex("StudentIdNumber")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("students");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.StudentSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ProficiencyLevel")
                        .HasColumnType("int")
                        .HasColumnName("proficiency_level");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("skill_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.Property<int?>("YearsOfExperience")
                        .HasColumnType("int")
                        .HasColumnName("years_of_experience");

                    b.HasKey("Id");

                    b.HasIndex("SkillId");

                    b.HasIndex("StudentId", "SkillId")
                        .IsUnique();

                    b.ToTable("student_skills");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bool")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Alumni", b =>
                {
                    b.HasOne("JobMatchAI.Domain.Entities.User", "User")
                        .WithOne("Alumni")
                        .HasForeignKey("JobMatchAI.Domain.Entities.Alumni", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Certification", b =>
                {
                    b.HasOne("JobMatchAI.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Employer", b =>
                {
                    b.HasOne("JobMatchAI.Domain.Entities.User", "User")
                        .WithOne("Employer")
                        .HasForeignKey("JobMatchAI.Domain.Entities.Employer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.EmploymentHistory", b =>
                {
                    b.HasOne("JobMatchAI.Domain.Entities.Alumni", "Alumni")
                        .WithMany("EmploymentHistory")
                        .HasForeignKey("AlumniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alumni");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Internship", b =>
                {
                    b.HasOne("JobMatchAI.Domain.Entities.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.JobPosting", b =>
                {
                    b.HasOne("JobMatchAI.Domain.Entities.Employer", "Employer")
                        .WithMany("JobPostings")
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.JobSkill", b =>
                {
                    b.HasOne("JobMatchAI.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("RequiredSkills")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobMatchAI.Domain.Entities.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.MatchResult", b =>
                {
                    b.HasOne("JobMatchAI.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("MatchResults")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobMatchAI.Domain.Entities.Student", "Student")
                        .WithMany("MatchResults")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.PlacementRecord", b =>
                {
                    b.HasOne("JobMatchAI.Domain.Entities.JobPosting", "JobPosting")
                        .WithMany("PlacementRecords")
                        .HasForeignKey("JobPostingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobMatchAI.Domain.Entities.Student", "Student")
                        .WithMany("PlacementRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPosting");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Skill", b =>
                {
                    b.HasOne("JobMatchAI.Domain.Entities.Alumni", null)
                        .WithMany("Skills")
                        .HasForeignKey("AlumniId");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Student", b =>
                {
                    b.HasOne("JobMatchAI.Domain.Entities.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("JobMatchAI.Domain.Entities.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.StudentSkill", b =>
                {
                    b.HasOne("JobMatchAI.Domain.Entities.Skill", "Skill")
                        .WithMany("StudentSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobMatchAI.Domain.Entities.Student", "Student")
                        .WithMany("StudentSkills")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Alumni", b =>
                {
                    b.Navigation("EmploymentHistory");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Employer", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.JobPosting", b =>
                {
                    b.Navigation("MatchResults");

                    b.Navigation("PlacementRecords");

                    b.Navigation("RequiredSkills");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Skill", b =>
                {
                    b.Navigation("JobSkills");

                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.Student", b =>
                {
                    b.Navigation("MatchResults");

                    b.Navigation("PlacementRecords");

                    b.Navigation("StudentSkills");
                });

            modelBuilder.Entity("JobMatchAI.Domain.Entities.User", b =>
                {
                    b.Navigation("Alumni");

                    b.Navigation("Employer");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
